
main: master.png
	convert master.png -resize 320x480 splash-iphone.png
	convert master.png -resize 640x960 splash-iphone_2x.png
	convert master.png -resize 640x1136 splash-iphone5.png
	convert master.png -resize 750x1334 splash-iphone6.png
	cp master.png splash-iphone6p_portrait.png
