
main: master.png
	convert master.png -resize 320x480 splash-iphone.png
	convert master.png -resize 640x960 splash-iphone_2x.png
	convert master.png -resize 640x1136 splash-iphone5.png
	convert master.png -resize 750x1334 splash-iphone6.png
	convert master.png -resize 200x320 splash-android-ldpi.png
	convert master.png -resize 320x480 splash-android-mdpi.png
	convert master.png -resize 480x800 splash-android-hdpi.png
	convert master.png -resize 720x1280 splash-android-xhdpi.png
	cp master.png splash-iphone6p_portrait.png
