
main: master.png
	convert master.png -resize 60x60 icon-iphone.png
	convert master.png -resize 120x120 icon-iphone_2x.png
	convert master.png -resize 180x180 icon-iphone_3x.png
	convert master.png -resize 36 icon-android-ldpi.png
	convert master.png -resize 48 icon-android-mdpi.png
	convert master.png -resize 72 icon-android-hdpi.png
	convert master.png -resize 96 icon-android-xhdpi.png
	convert master.png -resize 512 icon-android-play-store.png
